### ISSUE TITLE
Not working with minitest v4.7.0 on rails 3.2

### ISSUE THREAD

**Issue by mariozaizar** [tpope/fivemat#28]
Hello, I'm trying to use Fivemat with **minitest**, unfortunately this is an old version **v4.7.0** and upgrade to 5.x is impossible at the moment. 

I changed the `require 'minitest/autorun'` to `require 'fivemat/minitest/autorun'` and also the `require 'fivemat/minitest'` to `test/test_helper.rb` but I don't see any change in the output (still using the default formatter).

Any help is appreciated,
Thanks!

Mario

**Comment by tpope** [comment]
Can you check if `MiniTest::Unit.runner = Fivemat::MiniTest::Unit.new` fixes it?

**Comment by mariozaizar** [comment]
Actually I think I messed up the instructions somehow.. I just got it working doing only this changes:

```
# spec/helper.rb
require 'fivemat/minitest'

# test/helpers/test_helper.rb
require "fivemat/minitest"
```

With:
- minitest (4.7.5)
- minitest-rails (1.0.1)
- fivemat (1.3.2) 

Thanks for checking!
